name: Python package

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, 3.10.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-test.txt
    - name: Check with isort
      run: |
        isort zadnegoale tests --check-only
    - name: Check with Black Code Formatter
      run: |
        black zadnegoale tests --check
    - name: Lint with flake8
      run: |
        flake8 zadnegoale tests
    - name: Lint with pylint
      run: |
        pylint zadnegoale tests
    - name: Test with mypy
      run: |
        mypy zadnegoale
    - name: Test with pytest
      run: |
        python setup.py test
